package:
  name: tensorflow
  version: "1.4.0"

build:
  number: 0
  #  Google supplies whl files on PyPI for:
  # - Linux: Python 2.7, 3.3, 3.4, 3.5 and 3.6
  # - OS X: Python 2.7, 3.5 and 3.6
  # - Win-64: Python 3.5 and 3.6
  skip: True  # [win32]
  skip: True  # [win64 and py<35]
  skip: True  # [osx and py34]
  skip: True  # [py26]
  skip: True  # [py33]
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - enum34 >=1.1.6  # [py<34]
    - mock >=2.0.0    # [py27]
    - numpy >=1.12.1
    - protobuf >=3.3.0
    - six >=1.10.0
    - tensorboard >=0.4.0rc1,<0.5.0
    - libgcc          # [linux]

test:
  imports:
    - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

extra:
  recipe-maintainers:
    - jjhelmus
    - danielfrg
    - waitingkuo
    - ghego
    - hajapy
    - dhirschfeld
